name:                jenga
version:             0.1.0.0
description:         Redo of the jenga build system.
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/jenga.git

dependencies:
- MissingH
- base >= 4.7 && < 5
- containers
- data-ordlist
- directory
- filelock
- filepath
- optparse-applicative
- process
- safeio
- split
- unix

default-extensions:
- BangPatterns
- DuplicateRecordFields
- GADTs
- ImportQualifiedPost
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  jenga:
    main:                app/main.hs
    dependencies:        jenga
