name:                jenga2
version:             0.1.0.0
description:         Redo of the jenga build system.
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/jenga2.git

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- process
- split
- unix

default-extensions:
- DuplicateRecordFields
- GADTs
- ImportQualifiedPost
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        jenga2
